-- =============================================================
-- schema.sql
-- Database schema for the Web Systems Course application
-- Run via setup.php or import directly in phpMyAdmin / MySQL CLI
-- =============================================================

-- Create and select the database
CREATE DATABASE IF NOT EXISTS `websys`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `websys`;

-- -------------------------------------------------------------
-- Table: users
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
    `id`         INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `email`      VARCHAR(255)     NOT NULL,
    `password`   VARCHAR(255)     NOT NULL,
    `role`       ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    `created_at` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_users_email` (`email`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- Seed: default admin and user accounts
-- Password: Testing@123  (bcrypt — regenerated by setup.php)
-- The placeholder below is replaced at runtime by setup.php.
-- To import directly, replace {BCRYPT_PASSWORD} with a real hash.
-- -------------------------------------------------------------
INSERT IGNORE INTO `users` (`email`, `password`, `role`)
VALUES ('admin@websys.com', '$2y$10$lZG5TFndTC3uod2R0Ojc6uItvuDqtXSig3IRaXqwupagPcj.ivBU6', 'admin');

INSERT IGNORE INTO `users` (`email`, `password`, `role`)
VALUES ('user@websys.com', '$2y$10$LeEhTWGHfkio5fbIumIznuPn9bcHMqA7M2EVe0VcLXXYSMdYp/Ef2', 'user');
